# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b260617224d7c7bb32fc9fcfb6abc505626b55e1de59b628e0201663ae16bed7cbc3571915d20d29ef74471edb870c6f4f236729c97de20bdbb26d9f7a97690

test:
  secret_key_base: 6fbe611ab7f00eb427bac10ae3063ad47209c7eaaeca5ffcc471fb737442a1db777fa32aa817056f50ef60224ec9e500a23967afc7a92395d678624bbb30df5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
